### ISSUE TITLE
Buckets: Cannot read property 'NextContinuationToken' of undefined

### ISSUE THREAD

**Issue by Jolg42** [optoolco/beta#9]
I clicked on a bucket name and got this error reporting.

### STACK

```
TypeError: Cannot read property 'NextContinuationToken' of undefined
    at ObjectsIterator._fetchAndCache (app://otc/src/bundle.js:1:98784)
    at async ObjectsIterator.next (app://otc/src/bundle.js:1:99981)
    at async HTMLElement._prefetch (app://otc/src/bundle.js:1:235613)
    at async HTMLElement.prefetch (app://otc/src/bundle.js:1:234758)
    at async HTMLElement.fetchObjects (app://otc/src/bundle.js:1:124387)
    at async HTMLElement.refetchObjects (app://otc/src/bundle.js:1:124126)
```

### SYSTEM SUMMARY

```
Buckets v0.1.17
Darwin x64 19.6.0

Wizards: v0.1.17
Buckets: v0.1.9
Functions: v0.1.5
Data: v0.1.4
Electron: v11.1.1
```

**Comment by heapwolf** [comment]
Verified to be fixed.
